"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Warehouse_1 = require("./Warehouse");
var Vehicle_1 = require("./Vehicle");
var car1 = new Vehicle_1.Car(1000, 4, 120);
var car2 = new Vehicle_1.Car(500, 3, 90);
var car3 = new Vehicle_1.Car(2220, 2, 400);
var warehouse = new Warehouse_1.Warehouse(20);
warehouse.parkCar(car1);
warehouse.parkCar(car2);
warehouse.parkCar(car3);
console.log("current amount of cars: ".concat(warehouse.currentAmountOfCars()));
var car4 = warehouse.getCar(1);
console.log("current amount of cars: ".concat(warehouse.currentAmountOfCars()));
console.log("Capacity: ".concat(warehouse.capacity(), " "));
console.log(car2, car3);
